### ISSUE TITLE
annotate yaml file format and commands

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#103]
**Describe the bug**
When I try to set up an annotation task, I get and error saying the task is a file that cannot be found. 

The guidance for setting up an annotation task is 

1. To create and edit a YAML file:

2. Run the following setup in a notebook:

```
from mapreader.annotate.utils import prepare_annotation

userID="your_name"
annotation_tasks_file="./annotation_tasks.yaml"
task="rail_space"
annotation_set="test_one_inch_maps_001"

annotation=prepare_annotation(userID, annotation_tasks_file, task, annotation_set)
```
My YAML file looks like:

```
# ---------------------------------------
# Define an annotation task
# This includes: 
# 1. a name (e.g., building_simple or rail_space, see below)
# 2. a list of labels to be used for this task
# ---------------------------------------
tasks:
  coast:
    labels: ["Coast", "Other Water", "No"]
    
# ---------------------------------------
# paths 
# You need to specify:
# 1. a name (e.g., task_test_one_inch_maps_001, see below)
# 2. patch_paths: path to all the patches to be annotated 
# 3. parent_paths: path to the original/parent maps/images (which were patchified)
# 4. annot_dir: directory in which the outputs will be stored
# ---------------------------------------
paths:
  coastline_task:
    patch_paths: "./ts_downloaded_maps/patch_500_500/patch-*PNG"
    parent_paths: "./ts_downloaded_maps/*png"
    annot_dir: "./annotations_coastline"
```

And my notebook cell looks like:

```
from mapreader.annotate.utils import prepare_annotation

userID="katie"
annotation_tasks_file="annotation_tasks.yaml"
task="coastline_task"
annotation_set="test_one_inch_maps_001"

annotation=prepare_annotation(userID, annotation_tasks_file, task, annotation_set)
```

**To Reproduce**
1. Go to https://mapreader.readthedocs.io/en/rw_docs/User-guide/Annotate.html
4. Create new yaml file
5. Activate mr_py38 env, open notebook
6. See error

**Expected behavior**
This should run without an error so that I can annotate.

**Screenshots**
<img width="727" alt="Screen Shot 2023-03-09 at 08 58 56" src="https://user-images.githubusercontent.com/20363927/223971642-afbef55b-4856-4903-a3ed-1b06fc21fbd4.png">

**Desktop (please complete the following information):**
 - OS: old mac chip

**Additional context**
